# http://travis-ci.org/#!/ipython/ipython
language: python
python:
    - 3.4
    - 2.7
    - nightly
sudo: false
cache:
  directories:
    - $HOME/.cache/bower
    - $HOME/build/jupyter/notebook/jupyter_notebook/static/components
env:
  global:
    - PATH=$TRAVIS_BUILD_DIR/pandoc:$PATH
  matrix:
    - GROUP=python
    - GROUP=js/base
    - GROUP=js/notebook
    - GROUP=js/services
    - GROUP=js/tree
before_install:
    - 'if [[ $GROUP == js* ]]; then npm install -g casperjs; fi'
    - git clone --quiet --depth 1 https://github.com/minrk/travis-wheels travis-wheels
install:
    - pip install -f travis-wheels/wheelhouse -r requirements.txt coveralls
    - pip install -e file://$PWD#egg=jupyter_notebook[test]
    - ls $HOME/build/jupyter/notebook/jupyter_notebook/static/components
    - ls $HOME/build/jupyter/notebook/jupyter_notebook/static/
    - ls $HOME/build/jupyter/notebook/jupyter_notebook/
    - ls $HOME/build/jupyter/notebook/
    - ls $HOME/build/jupyter/
    - ls $HOME/build/
before_cache:
    - ls $HOME/build/jupyter/notebook/jupyter_notebook/static/components
    - ls $HOME/build/jupyter/notebook/jupyter_notebook/static/
    - ls $HOME/build/jupyter/notebook/jupyter_notebook/
    - ls $HOME/build/jupyter/notebook/
    - echo $HOME
    - pwd
script:
    - true # 'if [[ $GROUP == js* ]]; then python -m jupyter_notebook.jstest ${GROUP:3}; fi'
    - true # 'if [[ $GROUP == python ]]; then nosetests --with-coverage --cover-package=jupyter_notebook jupyter_notebook; fi'
matrix:
    include:
        - python: 3.3
          env: GROUP=python

after_success:
    - coveralls
