# http://travis-ci.org/#!/ipython/ipython
language: python

cache:
    directories:
        - $HOME/.cache/bower
        - $HOME/.cache/pip
python:
    - 3.6
    #- 2.7

sudo: required

addons:
  sauce_connect:
    username: "takluyver"
    access_key:
      secure: "GMF7zYsgRJK4fVpRhjYa2W09DyIC5CC2U5v253+aa7jFCnl+RN8mvJ0JJkGHvunBQkYzqHHtIXcOQ7Z5tuNGpySeHsEFC4V2wdYqrqfFTHhAXmRUrFW+A9AxzCokzv5nAKFrywktSYMZx01mf1PGFlJ6NY25tNXPY3SR7m0rHLQ="

env:
  global:
    - PATH=$TRAVIS_BUILD_DIR/pandoc:$PATH
  matrix:
    - GROUP=selenium
    #- GROUP=js/notebook
    #- GROUP=python
    #- GROUP=js/base
    #- GROUP=js/services
    #- GROUP=js/tree
    #- GROUP=docs

before_install:
    - pip install --upgrade pip
    - pip install --upgrade setuptools wheel nose coverage codecov
    - nvm install 6.9.2
    - nvm use 6.9.2
    - node --version
    - npm --version
    - npm upgrade -g npm
    - npm install
    - |
      if [[ $GROUP == js* ]]; then
        npm install -g casperjs@1.1.3 phantomjs-prebuilt@2.1.7
      fi
    - git clone --quiet --depth 1 https://github.com/minrk/travis-wheels travis-wheels
    - |
      if [[ $GROUP == docs ]]; then
        pip install -r docs/doc-requirements.txt
      fi
    - |
      if [[ $GROUP == selenium ]]; then
        pip install selenium
      fi

install:
    - pip install -f travis-wheels/wheelhouse file://$PWD#egg=notebook[test]
    - wget https://github.com/jgm/pandoc/releases/download/1.19.1/pandoc-1.19.1-1-amd64.deb && sudo dpkg -i pandoc-1.19.1-1-amd64.deb


script:
    - jupyter kernelspec list
    - |
      symlinks=$(find . -type l| grep -v './node_modules/' | grep -v './git-hooks')
      if [[ $(echo $symlinks) ]]; then
          echo "Repository contains symlinks which won't work on windows:"
          echo $symlinks
          echo ""
          false
      else
          true
      fi
    - 'if [[ $GROUP == js* ]]; then travis_retry python -m notebook.jstest ${GROUP:3}; fi'
    - 'if [[ $GROUP == python ]]; then nosetests -v --ignore-files tests/selenium --with-coverage --cover-package=notebook notebook; fi'
    - 'if [[ $GROUP == selenium ]]; then py.test -v notebook/tests/selenium; fi'
    - |
      if [[ $GROUP == docs ]]; then
        EXIT_STATUS=0
        make -C docs/ html || EXIT_STATUS=$?
        make -C docs/ linkcheck || EXIT_STATUS=$?
        pytest --nbval --current-env docs || EXIT_STATUS=$?
        exit $EXIT_STATUS
      fi


matrix:
#    include:
#        - python: 3.4
#          env: GROUP=python
#        - python: 3.5
#          env: GROUP=python
    exclude:
        - python: 2.7
          env: GROUP=docs

after_success:
    - codecov
