# miniconda bootstrap from conda-forge recipe
matrix:
  fast_finish: true

environment:
  matrix:
    - CONDA_PY: 36
      CONDA_PY_SPEC: ">=3.6,<3.7.0a0"
      CONDA_INSTALL_LOCN: "C:\\Miniconda36-x64"
    - CONDA_PY: 37
      CONDA_PY_SPEC: ">=3.7,<3.8.0a0"
      CONDA_INSTALL_LOCN: "C:\\Miniconda36-x64"
    - CONDA_PY: 38
      CONDA_PY_SPEC: ">=3.8,<3.9.0a0"
      CONDA_INSTALL_LOCN: "C:\\Miniconda36-x64"

platform:
  - x64

build: off

install:
  - cmd: call %CONDA_INSTALL_LOCN%\Scripts\activate.bat
  - cmd: conda config --set show_channel_urls true
  - cmd: conda config --add channels conda-forge
  #- cmd: conda update --yes --quiet conda
  - cmd: >-
      conda install -y
        "python %CONDA_PY_SPEC%"
        coverage
        ipykernel
        ipython_genutils
        jinja2
        jupyter_client
        jupyter_core
        nbconvert
        nbformat
        nbval
        nodejs
        nose
        nose-exclude
        pip
        prometheus_client
        pytest
        pytest-cov
        pyzmq
        requests
        selenium
        send2trash
        terminado
        tornado
        traitlets
  - cmd: python setup.py build
  # basically for nose_warnings_filter at this point
  - cmd: pip install .[test]

test_script:
  - nosetests  -v notebook --exclude-dir notebook\tests\selenium
