matrix:
  fast_finish: true

environment:
  CONDA_BUILD_DEPS: nodejs pip
  CONDA_RUN_DEPS: jinja2 tornado pyzmq ipython_genutils traitlets jupyter_core jupyter_client nbformat nbconvert ipykernel send2trash terminado prometheus_client
  CONDA_TEST_DEPS: nose nose-cov requests
  CUSTOM_CHANNELS: -c conda-forge -c defaults
  NOSE_EXCLUDE: selenium
  matrix:
    - CONDA_PY: 38
      CONDA_PY_SPEC: ">=3.8,<3.9.0a0"
      CONDA_INSTALL_LOCN: "C:\\Miniconda36-x64"
    - CONDA_PY: 37
      CONDA_PY_SPEC: ">=3.7,<3.8.0a0"
      CONDA_INSTALL_LOCN: "C:\\Miniconda36-x64"
    - CONDA_PY: 36
      CONDA_PY_SPEC: ">=3.6,<3.7.0a0"
      CONDA_INSTALL_LOCN: "C:\\Miniconda36-x64"

platform:
  - x64

build: off

install:
  - cmd: call %CONDA_INSTALL_LOCN%\Scripts\activate.bat
  - cmd: conda config --set show_channel_urls true
  - cmd: conda config --set always_yes true
  - cmd: conda upgrade conda
  - cmd: conda create -n notebook-test %CUSTOM_CHANNELS% "python %CONDA_PY_SPEC%" %CONDA_BUILD_DEPS% %CONDA_RUN_DEPS% %CONDA_TEST_DEPS% || exit 1
  - cmd: call %CONDA_INSTALL_LOCN%\Scripts\activate.bat notebook-test && python setup.py build
  - cmd: call %CONDA_INSTALL_LOCN%\Scripts\activate.bat notebook-test && python -m pip install . --no-deps

test_script:
  - call %CONDA_INSTALL_LOCN%\Scripts\activate.bat notebook-test && md tst_tmp && cd tst_tmp && nosetests -v notebook --with-cov --cov notebook --traverse-namespace
