# https://github.com/marketplace/actions/auto-author-assign
name: 'Auto Author Assign'

on:
  pull_request_target:
    types: [opened, reopened]

permissions:
  contents: read

jobs:
  assign-author:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: toshimaru/auto-author-assign@c1ffd6f64e20f8f5f61f4620a1e5f0b0908790ef # v2.0.1
