name: Update Playwright Snapshots

on:
  issue_comment:
    types: [created, edited]

permissions:
  contents: read

jobs:
  update-snapshots:
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, 'update playwright snapshots') }}
    runs-on: ubuntu-latest
    permissions:
      # Required by actions/update-snapshots
      contents: write
      pull-requests: write
    strategy:
      fail-fast: false
      matrix:
        browser: [firefox, chromium]

    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: React to the triggering comment
        run: |
          gh api repos/${{ github.repository }}/issues/comments/${{ github.event.comment.id }}/reactions --raw-field 'content=+1'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout the branch from the PR that triggered the job
        run: |
          # PR branch remote must be checked out using https URL
          git config --global hub.protocol https

          gh pr checkout ${{ github.event.issue.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Base Setup
        uses: jupyterlab/maintainer-tools/.github/actions/base-setup@4b05d5f62ffa18bed92d556309c86a95554401b9 # v1

      - name: Build
        uses: ./.github/actions/build-dist

      - uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
        with:
          name: notebook-dist-${{ github.run_number }}
          path: ./dist

      - name: Install the package
        run: |
          cd dist
          python -m pip install -vv notebook*.whl

          # disable git hooks
          git config core.hooksPath no-hooks

      - name: Install the test dependencies
        run: |
          cd ui-tests
          jlpm
          jlpm playwright install

      - name: Update snapshots
        uses: jupyterlab/maintainer-tools/.github/actions/update-snapshots@4b05d5f62ffa18bed92d556309c86a95554401b9 # v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          npm_client: jlpm
          test_folder: ui-tests
          start_server_script: 'null'
          update_script: test:update --browser ${{ matrix.browser }}
        env:
          DEBUG: pw:webserver
